### ISSUE TITLE
Create pages for footer links

### ISSUE THREAD

**Issue by jtomeck** [Kitware/vtkm-web#9]
1. Privacy Policy
2. Disclaimer
3. Contact

This will also need some functionality to distinguish between external and internal links. Right now it is prepending the baseurl.

**Comment by jtomeck** [comment]
@berkgeveci @kmorel There's no content for Privacy Policy and Disclaimer on the current site. Should I just get the footer links working properly, create pages for these and leave them for you guys to populate when you have content?

**Comment by kmorel** [comment]
The site is being hosted by a Kitware domain, so I think it makes sense to do whatever the Kitware legal team says is right. I note that the main VTK page points to https://www.kitware.com/privacy/#privacy-policy. It makes sense to me to use that, but @berkgeveci should make that decision.

**Comment by kmorel** [comment]
@berkgeveci I noticed that the links and text in the footer were still broken. I modified it using what is on the VTK page. If there should be something else, we can change that.
